version: '3.9'

x-php-cli: &php-cli
    build:
        context: ./php
        dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
        - ../:/var/project

services:
    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        container_name: ${COMPOSER_PROJECT_NAME}-nginx
        restart: unless-stopped
        tty: true
        ports:
            - ${NGINX_PORT}:80
        volumes:
            - ../:/var/project
        networks:
            - shortLink

    php-fpm:
        build:
            context: ./php
            dockerfile: Dockerfile
        container_name: ${COMPOSER_PROJECT_NAME}-php
        restart: unless-stopped
        # extra_hosts:
            # - "host.docker.internal:host-gateway"       # for Xdebug
        tty: true
        # environment:
            # PHP_IDE_CONFIG: "serverName=job-php-fpm"    # for Xdebug
        expose:
            - 9000
        volumes:
            - ../:/var/project
        networks:
            - shortLink

    postgres:
        image: postgres:12
        container_name: ${COMPOSER_PROJECT_NAME}-postgres
        restart: unless-stopped
        volumes:
            - ./postgres/data/:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: devdb
            POSTGRES_USER: devuser
            POSTGRES_PASSWORD: devsecret
            PGDATA: /var/lib/postgresql/data/pgdata
        ports:
            - ${POSTGRES_PORT}:5432
        networks:
            - shortLink

    # Node Service
    node:
        build: 
            context: ./node
            dockerfile: dockerfile
        container_name: ${COMPOSER_PROJECT_NAME}-node
        restart: unless-stopped
        tty: true
        volumes:
            - ../:/var/project
        networks: 
            - shortLink

    # RabbitMQ Service
    rabbitmq:
        image: rabbitmq:3.9.1-management
        container_name: ${COMPOSER_PROJECT_NAME}-rabbitmq
        restart: unless-stopped
        depends_on:
            - php-fpm
        links:
            - php-fpm
        # environment:
            # RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
            # RABBITMQ_DEFAULT_USER: guest # default: guest
            # RABBITMQ_DEFAULT_PASS: guest # default: guest
            # RABBITMQ_DEFAULT_VHOST: /
        ports:
            - ${RABBIT_MQ_MANAGEMENT}:15672
            - ${RABBIT_MQ_PORT}:5672
        networks:
            - shortLink

    # Queue Worker Service: default
    # queue-worker-default:
    #     <<: *php-cli
    #     container_name: job-queue-worker-default
    #     depends_on:
    #         - rabbitmq
    #     links:
    #         - rabbitmq
    #     command: ['./artisan', 'rabbitmq:consume', '--sleep=1', '--queue=default']
    #     networks:
    #         - shortLink

    # 

    # Queue Worker Service: links
    queue-worker-links:
        <<: *php-cli
        container_name: ${COMPOSER_PROJECT_NAME}-queue-worker-links
        depends_on:
            - rabbitmq
        links:
            - rabbitmq
        command: ['./artisan', 'rabbitmq:consume', '--queue=links', '--sleep=1']
        networks:
            - shortLink

    redoc:
        image: redocly/redoc
        container_name: ${COMPOSER_PROJECT_NAME}-redoc
        restart: unless-stopped
        tty: true
        volumes:
            - ../docs/:/usr/share/nginx/html/swagger/
        environment:
            - SPEC_URL=swagger/api-docs.yml
        ports:
            - 8084:80
            - 5554:8080
        networks:
            - shortLink

networks:
    shortLink:
        driver: bridge